# Configuration Yarn pour DTF Editor
# Compatible avec Yarn v1 et prêt pour v3+ si mise à jour nécessaire

# Activer les workspaces
enableGlobalCache: false

# Configuration des dépendances
preferInteractive: false

# Pour la compatibilité avec Render
enableTelemetry: false

# Configuration réseau
httpTimeout: 60000
networkTimeout: 60000

# Locking
enableImmutableCache: false
enableImmutableInstalls: false