services:
  - type: web
    name: graphite-dtf-fusion
    env: node
    plan: starter
    buildCommand: yarn install && yarn workspace @dtf-editor/shared build && yarn workspace @graphite-dtf-fusion/frontend build
    startCommand: npm run preview --workspace=frontend
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_APP_TITLE
        value: "Graphite DTF Fusion"
    staticPublishPath: ./frontend/dist
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /index.html
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html